Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib ipympl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import timedelta


from processing import *
from plotting import *
------------------


Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m~/mambaforge/envs/voters/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3526[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0;36m  Cell [0;32mIn[1], line 8[0;36m
[0;31m    from processing import *[0;36m

[0;36m  File [0;32m~/Documents/advocacy/voting/cambridge-voting-history/processing.py:175[0;36m[0m
[0;31m    voters_2012 = load_year(data_folder/"11.6.2012 StatePres 49ANP_103892.txt", data_folder/49VOT_103340 Nov 2012 election.txt")[0m
[0m                                                                                             ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid decimal literal


