Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

plt.figure()
age_grouped['voted'].loc[MUNICIPAL_YEARS].xs(group, level=1).plot(label=group, style='o--', color=colors[i])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m plt[38;5;241m.[39mfigure()
[0;32m----> 2[0m age_grouped[[38;5;124m'[39m[38;5;124mvoted[39m[38;5;124m'[39m][38;5;241m.[39mloc[MUNICIPAL_YEARS][38;5;241m.[39mxs([43mgroup[49m, level[38;5;241m=[39m[38;5;241m1[39m)[38;5;241m.[39mplot(label[38;5;241m=[39mgroup, style[38;5;241m=[39m[38;5;124m'[39m[38;5;124mo--[39m[38;5;124m'[39m, color[38;5;241m=[39mcolors[i])

[0;31mNameError[0m: name 'group' is not defined

